import React, { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Eye, EyeOff, Grid3X3, Handshake, ImagePlus, Images, Megaphone, MonitorSmartphone, Palette, PanelsTopLeft, Pencil, Plus, Trash2, UploadCloud, X } from "lucide-react";
import { api } from "../../../services/api";
import type { AppearanceSettings, HeroSlideItem, HomepageDestination, HomepagePartner, HomepageQuickAccessItem, HomepageServicesBanner, HomepageSideBanner, QuickAccessIcon } from "../../../types";

type Props = { value: AppearanceSettings; liveMode: boolean; onChange: (next: AppearanceSettings) => void; notify: (message: string) => void; };
type UploadTarget = `hero:${number}` | `side:${string}` | `quick:${string}` | "service" | `partner:${string}`;
type HomepageSection = "announcement" | "brand" | "hero" | "side" | "quick" | "services" | "partners";
type EditorTarget = { kind: "hero"; id: number } | { kind: "side"; id: string } | { kind: "quick"; id: string } | { kind: "service" } | { kind: "partner"; id: string } | null;

const MAX_BYTES = 2 * 1024 * 1024;
const supportedTypes = new Set(["image/jpeg", "image/png", "image/webp"]);
const destinations: Array<{ value: HomepageDestination; label: string }> = [{ value: "store", label: "فروشگاه / دسته‌بندی" }, { value: "services", label: "خدمات آنلاین" }, { value: "about", label: "دربارهٔ ما" }, { value: "contact", label: "تماس با ما" }];
const quickIconOptions: Array<{ value: QuickAccessIcon; label: string }> = [{ value: "wifi", label: "مودم و اینترنت" }, { value: "simcard", label: "سیم‌کارت" }, { value: "laptop", label: "لپ‌تاپ" }, { value: "network", label: "تجهیزات شبکه" }, { value: "services", label: "خدمات آنلاین" }, { value: "globe", label: "وب‌سایت" }, { value: "shopping-bag", label: "فروشگاه" }, { value: "tag", label: "تخفیف" }];
const sectionItems: Array<{ id: HomepageSection; title: string; description: string; Icon: typeof Images }> = [
  { id: "announcement", title: "بنر بالای سایت", description: "پیام، لینک و رنگ نوار بالای فروشگاه", Icon: Megaphone },
  { id: "brand", title: "رنگ‌بندی سایت", description: "رنگ اصلی دکمه‌ها، آیکون‌ها و حالت‌های انتخاب", Icon: Palette },
  { id: "hero", title: "اسلایدر اصلی", description: "اسلایدهای بزرگ ابتدای صفحه", Icon: PanelsTopLeft },
  { id: "side", title: "بنرهای کناری", description: "دو بنر کنار اسلایدر", Icon: Images },
  { id: "quick", title: "دسترسی سریع", description: "میان‌برها و آیکون‌ها", Icon: Grid3X3 },
  { id: "services", title: "خدمات آنلاین", description: "بنر معرفی خدمات", Icon: MonitorSmartphone },
  { id: "partners", title: "همکاران و برندها", description: "لوگوها و کارت‌های برند", Icon: Handshake },
];

const fallbackSidePromos = (value: AppearanceSettings): HomepageSideBanner[] => [
  { id: "side-1", title: value.sidePromo1Title, subtitle: value.sidePromo1Subtitle, image: value.sidePromo1Image, tag: value.sidePromo1Tag, actionText: "مشاهده", category: "simcard", destination: "store", overlayColor: "#1D4ED8", overlayOpacity: 68, isVisible: true },
  { id: "side-2", title: value.sidePromo2Title, subtitle: value.sidePromo2Subtitle, image: value.sidePromo2Image, tag: value.sidePromo2Tag, actionText: "مشاهده", category: "modem-internet", destination: "store", overlayColor: "#0F172A", overlayOpacity: 68, isVisible: true },
];
const fallbackQuickAccess: HomepageQuickAccessItem[] = [
  { id: "modem", title: "مودم", icon: "wifi", category: "modem-internet", destination: "store", isVisible: true }, { id: "simcard", title: "سیم‌کارت", icon: "simcard", category: "simcard", destination: "store", isVisible: true }, { id: "laptop", title: "لپ‌تاپ", icon: "laptop", category: "laptops", destination: "store", isVisible: true }, { id: "network", title: "تجهیزات شبکه", icon: "network", category: "networking-equipment", destination: "store", isVisible: true }, { id: "services", title: "خدمات آنلاین", icon: "services", category: "", destination: "services", isVisible: true },
];
const fallbackServicesBanner: HomepageServicesBanner = { title: "خدمات آنلاین نوین‌نت؛ سریع و هوشمند", description: "دسترسی آسان به خدمات دولتی و اداری، استعلامات برخط و سرویس‌های کاربردی بدون نوبت و در کمترین زمان.", image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80", primaryActionText: "مشاهده لیست خدمات", primaryDestination: "services", secondaryActionText: "راهنمای ثبت‌نام", secondaryDestination: "about", isVisible: true };
const fallbackPartners: HomepagePartner[] = [
  { id: "mci", name: "همراه اول", logoText: "MCI", subtitle: "بزرگترین اپراتور کشور", category: "", isVisible: true }, { id: "irancell", name: "ایرانسل", logoText: "Irancell", subtitle: "پیشرو در خدمات 5G", category: "", isVisible: true }, { id: "rightel", name: "رایتل", logoText: "RighTel", subtitle: "پیشگام دیتای همراه", category: "", isVisible: true }, { id: "shatel", name: "شاتل", logoText: "Shatel", subtitle: "اینترنت ثابت و فیبر نوری", category: "", isVisible: true }, { id: "huawei", name: "هوآوی", logoText: "Huawei", subtitle: "مودم و تجهیزات شبکه", category: "", isVisible: true },
];

function move<T>(items: T[], index: number, direction: -1 | 1): T[] { const target = index + direction; if (target < 0 || target >= items.length) return items; const next = [...items]; [next[index], next[target]] = [next[target], next[index]]; return next; }
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: "text" | "url" }) { return <label className="content-field"><span>{label}</span><input type={type} dir={type === "url" ? "ltr" : undefined} value={value ?? ""} onChange={(event) => onChange(event.target.value)} /></label>; }
function Textarea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="content-field content-field-wide"><span>{label}</span><textarea rows={3} value={value ?? ""} onChange={(event) => onChange(event.target.value)} /></label>; }
function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { const color = /^#[0-9a-fA-F]{6}$/.test(value) ? value : '#0F172A'; return <label className="content-field"><span>{label}</span><div className="flex items-center gap-2"><input aria-label={label} className="h-10 w-12 cursor-pointer rounded-lg border border-slate-200 bg-white p-1" type="color" value={color} onChange={(event) => onChange(event.target.value.toUpperCase())} /><input dir="ltr" className="min-w-0 flex-1" value={value ?? ""} maxLength={7} onChange={(event) => onChange(event.target.value)} placeholder="#2563EB" /></div></label>; }
function DestinationSelect({ value, onChange }: { value?: HomepageDestination; onChange: (value: HomepageDestination) => void }) { return <label className="content-field"><span>مقصد دکمه</span><select value={value ?? "store"} onChange={(event) => onChange(event.target.value as HomepageDestination)}>{destinations.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label>; }
function Upload({ label, imageUrl, uploading, onUpload, onRemove }: { label: string; imageUrl?: string; uploading: boolean; onUpload: (file: File) => void; onRemove: () => void }) { return <div className="content-image-upload content-field-wide"><div className="content-image-preview">{imageUrl ? <img src={imageUrl} alt={label} /> : <ImagePlus size={22} />}</div><div className="content-image-upload-copy"><strong>{label}</strong><small>{imageUrl ? "تصویر آمادهٔ نمایش است" : "هنوز تصویری انتخاب نشده است"}</small></div><label className="content-image-upload-button"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => { const file = event.currentTarget.files?.[0]; if (file) onUpload(file); event.currentTarget.value = ""; }} /><UploadCloud size={15} />{uploading ? "در حال بارگذاری…" : imageUrl ? "جایگزینی تصویر" : "انتخاب تصویر"}</label>{imageUrl && <button type="button" className="content-image-remove" onClick={onRemove}><Trash2 size={14} />حذف تصویر</button>}</div>; }

function CompactCard({ index, total, title, subtitle, image, visible, onEdit, onToggle, onMove, onRemove }: { key?: React.Key; index?: number; total?: number; title: string; subtitle: string; image?: string; visible: boolean; onEdit: () => void; onToggle: () => void; onMove?: (direction: -1 | 1) => void; onRemove?: () => void }) {
  return <article className="homepage-summary-card"><div className="homepage-summary-media">{image ? <img src={image} alt="" /> : <ImagePlus size={20} />}</div><div className="homepage-summary-copy">{index !== undefined && <small>مورد {index + 1}</small>}<strong>{title}</strong><span>{subtitle || "بدون توضیح"}</span></div><div className="homepage-summary-status"><span className={visible ? "shown" : "hidden"}>{visible ? <Eye size={13} /> : <EyeOff size={13} />}{visible ? "نمایش" : "مخفی"}</span></div><div className="homepage-summary-actions"><button type="button" className="homepage-edit-action" onClick={onEdit}><Pencil size={14} />ویرایش</button><button type="button" title={visible ? "مخفی کردن" : "نمایش دادن"} aria-label={visible ? "مخفی کردن" : "نمایش دادن"} onClick={onToggle}>{visible ? <EyeOff size={15} /> : <Eye size={15} />}</button>{onMove && <><button type="button" title="انتقال به بالا" aria-label="انتقال به بالا" disabled={index === undefined || index === 0} onClick={() => onMove(-1)}><ArrowUp size={15} /></button><button type="button" title="انتقال به پایین" aria-label="انتقال به پایین" disabled={index === undefined || total === undefined || index === total - 1} onClick={() => onMove(1)}><ArrowDown size={15} /></button></>}{onRemove && <button type="button" className="danger" title="حذف" aria-label="حذف مورد" onClick={onRemove}><Trash2 size={15} /></button>}</div></article>;
}

function EditorDialog({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="homepage-editor-overlay" role="presentation" onMouseDown={onClose}><section className="homepage-editor-dialog" role="dialog" aria-modal="true" aria-label={`ویرایش ${title}`} onMouseDown={(event) => event.stopPropagation()}><header><div><span>ویرایش متمرکز</span><h2>{title}</h2><p>فقط اطلاعات همین مورد را تغییر دهید؛ انتشار نهایی از دکمهٔ بالای صفحه انجام می‌شود.</p></div><button type="button" aria-label="بستن ویرایشگر" onClick={onClose}><X size={19} /></button></header><div className="homepage-editor-dialog-body">{children}</div><footer><button type="button" onClick={onClose}>بستن و ادامهٔ ویرایش</button></footer></section></div>; }

export function HomepageContentManagementPage({ value, liveMode, onChange, notify }: Props) {
  const [activeSection, setActiveSection] = useState<HomepageSection>("hero");
  const [editing, setEditing] = useState<EditorTarget>(null);
  const [uploadingTarget, setUploadingTarget] = useState<UploadTarget | null>(null);
  const sidePromos = useMemo(() => value.sidePromos !== undefined ? value.sidePromos : fallbackSidePromos(value), [value]);
  const quickAccessItems = useMemo(() => value.quickAccessItems !== undefined ? value.quickAccessItems : fallbackQuickAccess, [value.quickAccessItems]);
  const servicesBanner = value.servicesBanner ?? fallbackServicesBanner;
  const partners = useMemo(() => value.partners !== undefined ? value.partners : fallbackPartners, [value.partners]);
  const heroSlides = value.heroSlides ?? [];
  const activeMeta = sectionItems.find((section) => section.id === activeSection)!;
  const patch = (updates: Partial<AppearanceSettings>) => onChange({ ...value, ...updates });
  const upload = async (file: File, target: UploadTarget, setUrl: (url: string) => void) => { if (!supportedTypes.has(file.type)) return notify("فقط تصویر JPG، PNG یا WEBP قابل بارگذاری است."); if (file.size > MAX_BYTES) return notify("حجم هر تصویر صفحهٔ اصلی حداکثر ۲ مگابایت است."); setUploadingTarget(target); try { const url = liveMode ? await api.uploadAdminSiteMediaImage(file) : URL.createObjectURL(file); setUrl(url); notify(liveMode ? "تصویر بارگذاری شد؛ برای انتشار نهایی ذخیره کنید." : "پیش‌نمایش تصویر در دادهٔ نمونه به‌روزرسانی شد."); } catch (error) { notify(error instanceof Error ? error.message : "بارگذاری تصویر انجام نشد."); } finally { setUploadingTarget(null); } };
  const patchHero = (id: number, updates: Partial<HeroSlideItem>) => patch({ heroSlides: heroSlides.map((item) => item.id === id ? { ...item, ...updates } : item) });
  const patchSide = (id: string, updates: Partial<HomepageSideBanner>) => patch({ sidePromos: sidePromos.map((item) => item.id === id ? { ...item, ...updates } : item) });
  const patchQuick = (id: string, updates: Partial<HomepageQuickAccessItem>) => patch({ quickAccessItems: quickAccessItems.map((item) => item.id === id ? { ...item, ...updates } : item) });
  const patchPartner = (id: string, updates: Partial<HomepagePartner>) => patch({ partners: partners.map((item) => item.id === id ? { ...item, ...updates } : item) });
  const confirmRemove = (label: string, action: () => void) => { if (window.confirm(`«${label}» حذف شود؟`)) action(); };
  const selectedHero = editing?.kind === "hero" ? heroSlides.find((item) => item.id === editing.id) : undefined;
  const selectedSide = editing?.kind === "side" ? sidePromos.find((item) => item.id === editing.id) : undefined;
  const selectedQuick = editing?.kind === "quick" ? quickAccessItems.find((item) => item.id === editing.id) : undefined;
  const selectedPartner = editing?.kind === "partner" ? partners.find((item) => item.id === editing.id) : undefined;

  const addHero = () => { const id = Date.now(); patch({ heroSlides: [...heroSlides, { id, title: "اسلاید جدید", subtitle: "توضیح کوتاه اسلاید", image: "", actionText: "مشاهده", category: "", badge: "پیشنهاد ویژه", destination: "store", customUrl: "", overlayColor: "#0F172A", overlayOpacity: 72, isVisible: true }] }); setEditing({ kind: "hero", id }); };
  const addSide = () => { const id = `side-${Date.now()}`; patch({ sidePromos: [...sidePromos, { id, title: "بنر جدید", subtitle: "توضیح کوتاه", image: "", tag: "پیشنهاد ویژه", actionText: "مشاهده", category: "", destination: "store", customUrl: "", overlayColor: "#0F172A", overlayOpacity: 68, isVisible: true }] }); setEditing({ kind: "side", id }); };
  const addQuick = () => { const id = `quick-${Date.now()}`; patch({ quickAccessItems: [...quickAccessItems, { id, title: "دسترسی جدید", icon: "globe", imageUrl: "", category: "", destination: "store", customUrl: "", isVisible: true }] }); setEditing({ kind: "quick", id }); };
  const addPartner = () => { const id = `partner-${Date.now()}`; patch({ partners: [...partners, { id, name: "همکار جدید", logoText: "LOGO", logoImage: "", subtitle: "توضیح کوتاه", category: "", customUrl: "", isVisible: true }] }); setEditing({ kind: "partner", id }); };

  return <div className="homepage-content-manager"><div className="homepage-section-intro"><div><span>مدیریت بخش‌بخش</span><h2>هر قسمت صفحهٔ اصلی را جداگانه و منظم ویرایش کنید</h2><p>هر بخش ابتدا یک فهرست خلاصه دارد. برای ویرایش هر مورد روی «ویرایش» بزنید تا فقط فرم همان مورد باز شود.</p></div></div><nav className="homepage-section-tabs" aria-label="بخش‌های قابل مدیریت صفحهٔ اصلی">{sectionItems.map(({ id, title, description, Icon }) => <button type="button" key={id} className={activeSection === id ? "active" : ""} aria-pressed={activeSection === id} onClick={() => setActiveSection(id)}><Icon size={19} /><span><strong>{title}</strong><small>{description}</small></span></button>)}</nav><section className="homepage-section-panel"><header className="homepage-section-panel-heading"><div><span>بخش انتخاب‌شده</span><h2>{activeMeta.title}</h2><p>{activeMeta.description}</p></div></header>

    {activeSection === "announcement" && <div className="homepage-section-body"><div className="content-editor-grid"><label className="content-field content-field-wide"><span>نمایش بنر بالای سایت</span><button type="button" className={value.topBannerEnabled ? "w-full rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2.5 text-right text-xs font-bold text-emerald-700" : "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-right text-xs font-bold text-slate-600"} aria-pressed={value.topBannerEnabled} onClick={() => patch({ topBannerEnabled: !value.topBannerEnabled })}>{value.topBannerEnabled ? "فعال است؛ برای حذف از سایت بزنید" : "غیرفعال است؛ برای نمایش در سایت بزنید"}</button></label><Textarea label="متن بنر" value={value.topBannerText} onChange={(topBannerText) => patch({ topBannerText })} /><ColorField label="رنگ پس‌زمینه" value={value.topBannerBgColor} onChange={(topBannerBgColor) => patch({ topBannerBgColor })} /><ColorField label="رنگ متن" value={value.topBannerTextColor} onChange={(topBannerTextColor) => patch({ topBannerTextColor })} /><Field label="متن لینک (اختیاری)" value={value.topBannerLinkText} onChange={(topBannerLinkText) => patch({ topBannerLinkText })} /><Field label="لینک بنر یا دکمه (اختیاری)" type="url" value={value.topBannerLinkUrl} onChange={(topBannerLinkUrl) => patch({ topBannerLinkUrl })} /></div></div>}
    {activeSection === "brand" && <div className="homepage-section-body"><div className="content-editor-grid"><div className="content-field content-field-wide"><span className="mb-2 block text-xs font-bold text-slate-700">رنگ‌بندی عمومی فروشگاه</span><p className="mb-3 text-[11px] leading-5 text-slate-500">این سه رنگ روی دکمه‌ها، آیکون‌ها، لینک‌ها و حالت‌های انتخاب storefront اعمال می‌شوند.</p></div><ColorField label="رنگ اصلی" value={value.brandPrimaryColor ?? "#2563EB"} onChange={(brandPrimaryColor) => patch({ brandPrimaryColor })} /><ColorField label="رنگ دوم" value={value.brandSecondaryColor ?? "#1D4ED8"} onChange={(brandSecondaryColor) => patch({ brandSecondaryColor })} /><ColorField label="رنگ تأکیدی" value={value.brandAccentColor ?? "#DC2626"} onChange={(brandAccentColor) => patch({ brandAccentColor })} /></div></div>}
    {activeSection === "hero" && <div className="homepage-section-body"><div className="homepage-section-actions"><p>برای تغییر یک اسلاید، کارت آن را انتخاب کنید.</p><button type="button" className="content-social-add" onClick={addHero}><Plus size={15} />افزودن اسلاید</button></div><div className="homepage-summary-list">{heroSlides.map((item, index) => <CompactCard key={item.id} index={index} total={heroSlides.length} title={item.title} subtitle={item.badge} image={item.image} visible={item.isVisible !== false} onEdit={() => setEditing({ kind: "hero", id: item.id })} onToggle={() => patchHero(item.id, { isVisible: item.isVisible === false })} onMove={(direction) => patch({ heroSlides: move(heroSlides, index, direction) })} onRemove={() => confirmRemove(item.title, () => patch({ heroSlides: heroSlides.filter((entry) => entry.id !== item.id) }))} />)}</div></div>}
    {activeSection === "side" && <div className="homepage-section-body"><div className="homepage-section-actions"><p>بنرهای کنار اسلایدر را از این فهرست مدیریت کنید.</p><button type="button" className="content-social-add" onClick={addSide}><Plus size={15} />افزودن بنر</button></div><div className="homepage-summary-list">{sidePromos.map((item, index) => <CompactCard key={item.id} index={index} total={sidePromos.length} title={item.title} subtitle={item.tag} image={item.image} visible={item.isVisible} onEdit={() => setEditing({ kind: "side", id: item.id })} onToggle={() => patchSide(item.id, { isVisible: !item.isVisible })} onMove={(direction) => patch({ sidePromos: move(sidePromos, index, direction) })} onRemove={() => confirmRemove(item.title, () => patch({ sidePromos: sidePromos.filter((entry) => entry.id !== item.id) }))} />)}</div></div>}
    {activeSection === "quick" && <div className="homepage-section-body"><div className="homepage-section-actions"><p>میان‌برها در فهرست کوتاه هستند و هر مورد editor مخصوص خود را دارد.</p><button type="button" className="content-social-add" onClick={addQuick}><Plus size={15} />افزودن دسترسی</button></div><div className="homepage-summary-list">{quickAccessItems.map((item, index) => <CompactCard key={item.id} index={index} total={quickAccessItems.length} title={item.title} subtitle={quickIconOptions.find((icon) => icon.value === item.icon)?.label ?? "آیکون انتخاب‌شده"} image={item.imageUrl} visible={item.isVisible} onEdit={() => setEditing({ kind: "quick", id: item.id })} onToggle={() => patchQuick(item.id, { isVisible: !item.isVisible })} onMove={(direction) => patch({ quickAccessItems: move(quickAccessItems, index, direction) })} onRemove={() => confirmRemove(item.title, () => patch({ quickAccessItems: quickAccessItems.filter((entry) => entry.id !== item.id) }))} />)}</div></div>}
    {activeSection === "services" && <div className="homepage-section-body"><p className="homepage-section-helper">این بخش فقط یک بنر دارد. برای نمایش فرم مرتب و کامل روی «ویرایش» بزنید.</p><div className="homepage-single-summary"><CompactCard title={servicesBanner.title} subtitle={servicesBanner.primaryActionText} image={servicesBanner.image} visible={servicesBanner.isVisible} onEdit={() => setEditing({ kind: "service" })} onToggle={() => patch({ servicesBanner: { ...servicesBanner, isVisible: !servicesBanner.isVisible } })} /></div></div>}
    {activeSection === "partners" && <div className="homepage-section-body"><div className="homepage-section-actions"><p>هر کارت برند جداگانه ویرایش می‌شود تا فهرست لوگوها مرتب بماند.</p><button type="button" className="content-social-add" onClick={addPartner}><Plus size={15} />افزودن همکار</button></div><div className="homepage-summary-list">{partners.map((item, index) => <CompactCard key={item.id} index={index} total={partners.length} title={item.name} subtitle={item.subtitle} image={item.logoImage} visible={item.isVisible} onEdit={() => setEditing({ kind: "partner", id: item.id })} onToggle={() => patchPartner(item.id, { isVisible: !item.isVisible })} onMove={(direction) => patch({ partners: move(partners, index, direction) })} onRemove={() => confirmRemove(item.name, () => patch({ partners: partners.filter((entry) => entry.id !== item.id) }))} />)}</div></div>}
  </section>

  {selectedHero && <EditorDialog title={selectedHero.title || "اسلاید"} onClose={() => setEditing(null)}><div className="content-editor-grid"><Upload label="تصویر اسلاید" imageUrl={selectedHero.image} uploading={uploadingTarget === `hero:${selectedHero.id}`} onUpload={(file) => void upload(file, `hero:${selectedHero.id}`, (image) => patchHero(selectedHero.id, { image }))} onRemove={() => patchHero(selectedHero.id, { image: "" })} /><ColorField label="رنگ لایهٔ روی تصویر" value={selectedHero.overlayColor ?? "#0F172A"} onChange={(overlayColor) => patchHero(selectedHero.id, { overlayColor })} /><label className="content-field"><span>شفافیت لایه: {(selectedHero.overlayOpacity ?? 72).toLocaleString('fa-IR')}٪</span><input type="range" min="0" max="100" step="1" value={selectedHero.overlayOpacity ?? 72} onChange={(event) => patchHero(selectedHero.id, { overlayOpacity: Number(event.target.value) })} /></label><Field label="برچسب" value={selectedHero.badge} onChange={(badge) => patchHero(selectedHero.id, { badge })} /><Field label="عنوان" value={selectedHero.title} onChange={(title) => patchHero(selectedHero.id, { title })} /><Textarea label="توضیح" value={selectedHero.subtitle} onChange={(subtitle) => patchHero(selectedHero.id, { subtitle })} /><Field label="متن دکمه" value={selectedHero.actionText} onChange={(actionText) => patchHero(selectedHero.id, { actionText })} /><DestinationSelect value={selectedHero.destination} onChange={(destination) => patchHero(selectedHero.id, { destination })} /><Field label="لینک دلخواه (اختیاری)" type="url" value={selectedHero.customUrl ?? ""} onChange={(customUrl) => patchHero(selectedHero.id, { customUrl })} /><Field label="شناسه دسته‌بندی (برای فروشگاه)" value={selectedHero.category} onChange={(category) => patchHero(selectedHero.id, { category })} /></div></EditorDialog>}
  {selectedSide && <EditorDialog title={selectedSide.title || "بنر کناری"} onClose={() => setEditing(null)}><div className="content-editor-grid"><Upload label="تصویر بنر" imageUrl={selectedSide.image} uploading={uploadingTarget === `side:${selectedSide.id}`} onUpload={(file) => void upload(file, `side:${selectedSide.id}`, (image) => patchSide(selectedSide.id, { image }))} onRemove={() => patchSide(selectedSide.id, { image: "" })} /><ColorField label="رنگ لایهٔ روی بنر" value={selectedSide.overlayColor ?? "#0F172A"} onChange={(overlayColor) => patchSide(selectedSide.id, { overlayColor })} /><label className="content-field"><span>شفافیت لایه: {(selectedSide.overlayOpacity ?? 68).toLocaleString('fa-IR')}٪</span><input type="range" min="0" max="100" step="1" value={selectedSide.overlayOpacity ?? 68} onChange={(event) => patchSide(selectedSide.id, { overlayOpacity: Number(event.target.value) })} /></label><Field label="برچسب" value={selectedSide.tag} onChange={(tag) => patchSide(selectedSide.id, { tag })} /><Field label="عنوان" value={selectedSide.title} onChange={(title) => patchSide(selectedSide.id, { title })} /><Textarea label="توضیح" value={selectedSide.subtitle} onChange={(subtitle) => patchSide(selectedSide.id, { subtitle })} /><Field label="متن دکمه" value={selectedSide.actionText} onChange={(actionText) => patchSide(selectedSide.id, { actionText })} /><DestinationSelect value={selectedSide.destination} onChange={(destination) => patchSide(selectedSide.id, { destination })} /><Field label="لینک دلخواه (اختیاری)" type="url" value={selectedSide.customUrl ?? ""} onChange={(customUrl) => patchSide(selectedSide.id, { customUrl })} /><Field label="شناسه دسته‌بندی (برای فروشگاه)" value={selectedSide.category} onChange={(category) => patchSide(selectedSide.id, { category })} /></div></EditorDialog>}
  {selectedQuick && <EditorDialog title={selectedQuick.title || "دسترسی سریع"} onClose={() => setEditing(null)}><div className="content-editor-grid"><Upload label="تصویر یا لوگو" imageUrl={selectedQuick.imageUrl} uploading={uploadingTarget === `quick:${selectedQuick.id}`} onUpload={(file) => void upload(file, `quick:${selectedQuick.id}`, (imageUrl) => patchQuick(selectedQuick.id, { imageUrl }))} onRemove={() => patchQuick(selectedQuick.id, { imageUrl: "" })} /><Field label="عنوان" value={selectedQuick.title} onChange={(title) => patchQuick(selectedQuick.id, { title })} /><label className="content-field"><span>آیکون پیش‌فرض</span><select value={selectedQuick.icon} onChange={(event) => patchQuick(selectedQuick.id, { icon: event.target.value as QuickAccessIcon })}>{quickIconOptions.map((icon) => <option value={icon.value} key={icon.value}>{icon.label}</option>)}</select></label><DestinationSelect value={selectedQuick.destination} onChange={(destination) => patchQuick(selectedQuick.id, { destination })} /><Field label="لینک دلخواه (اختیاری)" type="url" value={selectedQuick.customUrl ?? ""} onChange={(customUrl) => patchQuick(selectedQuick.id, { customUrl })} /><Field label="شناسه دسته‌بندی (برای فروشگاه)" value={selectedQuick.category} onChange={(category) => patchQuick(selectedQuick.id, { category })} /></div></EditorDialog>}
  {editing?.kind === "service" && <EditorDialog title="بنر خدمات آنلاین" onClose={() => setEditing(null)}><div className="content-editor-grid"><Upload label="تصویر بنر خدمات آنلاین" imageUrl={servicesBanner.image} uploading={uploadingTarget === "service"} onUpload={(file) => void upload(file, "service", (image) => patch({ servicesBanner: { ...servicesBanner, image } }))} onRemove={() => patch({ servicesBanner: { ...servicesBanner, image: "" } })} /><Field label="عنوان" value={servicesBanner.title} onChange={(title) => patch({ servicesBanner: { ...servicesBanner, title } })} /><Textarea label="توضیح" value={servicesBanner.description} onChange={(description) => patch({ servicesBanner: { ...servicesBanner, description } })} /><Field label="متن دکمهٔ اصلی" value={servicesBanner.primaryActionText} onChange={(primaryActionText) => patch({ servicesBanner: { ...servicesBanner, primaryActionText } })} /><DestinationSelect value={servicesBanner.primaryDestination} onChange={(primaryDestination) => patch({ servicesBanner: { ...servicesBanner, primaryDestination } })} /><Field label="لینک دکمهٔ اصلی (اختیاری)" type="url" value={servicesBanner.primaryCustomUrl ?? ""} onChange={(primaryCustomUrl) => patch({ servicesBanner: { ...servicesBanner, primaryCustomUrl } })} /><Field label="متن دکمهٔ دوم" value={servicesBanner.secondaryActionText} onChange={(secondaryActionText) => patch({ servicesBanner: { ...servicesBanner, secondaryActionText } })} /><DestinationSelect value={servicesBanner.secondaryDestination} onChange={(secondaryDestination) => patch({ servicesBanner: { ...servicesBanner, secondaryDestination } })} /><Field label="لینک دکمهٔ دوم (اختیاری)" type="url" value={servicesBanner.secondaryCustomUrl ?? ""} onChange={(secondaryCustomUrl) => patch({ servicesBanner: { ...servicesBanner, secondaryCustomUrl } })} /></div></EditorDialog>}
  {selectedPartner && <EditorDialog title={selectedPartner.name || "همکار"} onClose={() => setEditing(null)}><div className="content-editor-grid"><Upload label="لوگو یا تصویر" imageUrl={selectedPartner.logoImage} uploading={uploadingTarget === `partner:${selectedPartner.id}`} onUpload={(file) => void upload(file, `partner:${selectedPartner.id}`, (logoImage) => patchPartner(selectedPartner.id, { logoImage }))} onRemove={() => patchPartner(selectedPartner.id, { logoImage: "" })} /><Field label="نام برند یا همکار" value={selectedPartner.name} onChange={(name) => patchPartner(selectedPartner.id, { name })} /><Field label="متن جایگزین لوگو" value={selectedPartner.logoText} onChange={(logoText) => patchPartner(selectedPartner.id, { logoText })} /><Field label="توضیح کوتاه" value={selectedPartner.subtitle} onChange={(subtitle) => patchPartner(selectedPartner.id, { subtitle })} /><Field label="شناسه دسته‌بندی (اختیاری)" value={selectedPartner.category} onChange={(category) => patchPartner(selectedPartner.id, { category })} /><Field label="لینک دلخواه کارت (اختیاری)" type="url" value={selectedPartner.customUrl ?? ""} onChange={(customUrl) => patchPartner(selectedPartner.id, { customUrl })} /></div></EditorDialog>}
</div>;
}
