// Design: Novinet's online-services workspace is a compact content-operations tool. Services are informational pages with external contact only—never API-driven workflows.
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { ArrowRight, BookOpenCheck, CheckCircle2, ChevronLeft, CircleHelp, ClipboardCheck, ExternalLink, FileText, Globe2, ListChecks, Pencil, Plus, Save, Send, ShieldCheck, Trash2, X } from "lucide-react";
import { AppSelect } from "./AppSelect";
import type { ServiceCategoryItem } from "../../../types";
import "./online-services.css";
import "./online-services-review.css";
import "./online-service-actions.css";

export type ServiceStatus = "پیش‌نویس" | "منتشرشده";
export type ContactType = "تلگرام" | "واتس‌اپ" | "شماره تماس" | "لینک بیرونی";
export type OnlineService = { id: number; title: string; slug: string; category: string; serviceCategoryId: number; summary: string; body: string; documents: string[]; steps: string[]; faq: Array<{ question: string; answer: string }>; contactType: ContactType; contactUrl: string; ctaLabel: string; status: ServiceStatus; updated: string };
type ServiceDraft = Omit<OnlineService, "id" | "updated">;

const emptyDraft: ServiceDraft = { title: "", slug: "", category: "", serviceCategoryId: 0, summary: "", body: "", documents: [], steps: [], faq: [], contactType: "تلگرام", contactUrl: "", ctaLabel: "ادامه در تلگرام", status: "پیش‌نویس" };
const normalizeText = (value: string) => value.trim().replace(/\s+/g, " ");

export function OnlineServicesPage({ rows, categories, query, setQuery, onNew, onEdit, onDelete, onManageCategories, loading = false }: { rows: OnlineService[]; categories: ServiceCategoryItem[]; query: string; setQuery: (value: string) => void; onNew: () => void; onEdit: (service: OnlineService) => void; onDelete: (service: OnlineService) => void; onManageCategories: () => void; loading?: boolean }) {
  const [filter, setFilter] = useState<"همه" | ServiceStatus>("همه");
  const filtered = useMemo(() => rows.filter((row) => (filter === "همه" || row.status === filter) && `${row.title} ${row.category} ${row.slug}`.toLocaleLowerCase("fa-IR").includes(query.toLocaleLowerCase("fa-IR"))), [rows, filter, query]);
  const published = rows.filter((row) => row.status === "منتشرشده").length;
  return <section className="services-workspace">
    <header className="services-command"><div><span><Globe2 size={16} />راهنما و ارتباط بیرونی</span><h1>خدمات آنلاین</h1><p>هر خدمت یک صفحهٔ محتوایی مستقل است؛ هیچ API یا اطلاعات حساس در این بخش وجود ندارد.</p></div><div className="flex gap-2"><button className="editor-cancel" onClick={onManageCategories}>مدیریت دسته‌ها</button><button className="service-primary" disabled={!categories.some((category) => category.is_active)} onClick={onNew}><Plus size={16} />خدمت جدید</button></div></header>
    <div className="services-summary"><span><small>کل خدمات</small><b>{rows.length.toLocaleString("fa-IR")}</b></span><span><small>منتشرشده</small><b className="green">{published.toLocaleString("fa-IR")}</b></span><span><small>پیش‌نویس</small><b className="amber">{(rows.length - published).toLocaleString("fa-IR")}</b></span><span><small>روش تحویل</small><b>راهنما + ارتباط</b></span></div>
    <div className="services-toolbar"><label><FileText size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="جست‌وجوی عنوان یا دستهٔ خدمت" /></label><div>{(["همه", "منتشرشده", "پیش‌نویس"] as const).map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div></div>
    <section className="service-list-panel"><header><span>فهرست خدمات</span><small>{loading ? "در حال بارگذاری…" : `${filtered.length.toLocaleString("fa-IR")} مورد مطابق فیلتر`}</small></header>{loading ? <div className="services-empty"><FileText size={24} /><b>در حال دریافت خدمات آنلاین…</b></div> : filtered.length ? <div className="service-list">{filtered.map((service) => <article key={service.id}><span className="service-file-mark"><FileText size={17} /></span><div className="service-list-copy"><b>{service.title}</b><small>{service.category} <i>·</i> <span dir="ltr">/services/{service.slug}</span></small></div><em className={service.status === "منتشرشده" ? "published" : "draft"}>{service.status}</em><span className="service-contact"><ExternalLink size={13} />{service.contactType}</span><small className="service-updated">{service.updated}</small><button className="service-row-edit" aria-label={`ویرایش ${service.title}`} title="ویرایش" onClick={() => onEdit(service)}><Pencil size={15} /></button><button className="service-row-edit service-row-delete" aria-label={`حذف ${service.title}`} title="حذف" onClick={() => onDelete(service)}><Trash2 size={15} /></button></article>)}</div> : <div className="services-empty"><FileText size={24} /><b>خدمتی با این فیلتر پیدا نشد.</b><button onClick={onNew}>افزودن خدمت</button></div>}</section>
  </section>;
}

export function OnlineServiceEditor({ service, categories, existingSlugs, onClose, onSave }: { service: OnlineService | null; categories: ServiceCategoryItem[]; existingSlugs: string[]; onClose: () => void; onSave: (service: OnlineService) => Promise<void> | void }) {
  const [draft, setDraft] = useState<ServiceDraft>(() => service ? { title: service.title, slug: service.slug, category: service.category, serviceCategoryId: service.serviceCategoryId, summary: service.summary, body: service.body, documents: service.documents, steps: service.steps, faq: service.faq, contactType: service.contactType, contactUrl: service.contactUrl, ctaLabel: service.ctaLabel, status: service.status } : { ...emptyDraft, serviceCategoryId: categories.find((category) => category.is_active)?.id ?? 0 });
  const [section, setSection] = useState<"هویت" | "محتوا" | "راهنما" | "ارتباط">("هویت");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const update = <K extends keyof ServiceDraft>(key: K, value: ServiceDraft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const cleanList = (items: string[]) => items.map(normalizeText).filter(Boolean).slice(0, 12);
  const validate = (status: ServiceStatus) => { const title = normalizeText(draft.title); const slug = normalizeText(draft.slug).toLowerCase(); const summary = normalizeText(draft.summary); const contactUrl = normalizeText(draft.contactUrl); if (!title) return "عنوان خدمت را وارد کنید."; if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) return "slug باید انگلیسی، کوچک و با خط تیره باشد."; if (existingSlugs.includes(slug)) return "این slug برای خدمت دیگری استفاده شده است."; if (!draft.serviceCategoryId) return "دستهٔ خدمت را انتخاب کنید."; if (!summary) return "توضیح کوتاه خدمت را وارد کنید."; if (!contactUrl) return "مسیر ارتباط را وارد کنید."; if (draft.contactType === "شماره تماس" ? !/^tel:\+?[0-9]+$/.test(contactUrl) : !/^https:\/\/.+/.test(contactUrl)) return draft.contactType === "شماره تماس" ? "شماره تماس باید با tel: شروع شود؛ مانند tel:+982100000000" : "مسیر ارتباط باید URL امن HTTPS باشد."; return ""; };
  const submit = async (status: ServiceStatus) => { const issue = validate(status); const category = categories.find((item) => item.id === draft.serviceCategoryId); if (issue || !category) { setError(issue || "دستهٔ خدمت پیدا نشد."); return; } const saved: OnlineService = { id: service?.id ?? 0, title: normalizeText(draft.title), slug: normalizeText(draft.slug).toLowerCase(), category: category.name, serviceCategoryId: category.id, summary: normalizeText(draft.summary), body: draft.body.trim(), documents: cleanList(draft.documents), steps: cleanList(draft.steps), faq: draft.faq.map((item) => ({ question: normalizeText(item.question), answer: item.answer.trim() })).filter((item) => item.question && item.answer).slice(0, 12), contactType: draft.contactType, contactUrl: normalizeText(draft.contactUrl), ctaLabel: normalizeText(draft.ctaLabel) || "دریافت راهنمایی", status, updated: service?.updated ?? "اکنون" }; setSaving(true); setError(""); try { await onSave(saved); } catch (cause) { setError(cause instanceof Error ? cause.message : "ذخیرهٔ خدمت انجام نشد."); } finally { setSaving(false); } };
  const addListItem = (key: "documents" | "steps") => update(key, [...draft[key], ""]);
  const setListItem = (key: "documents" | "steps", index: number, value: string) => update(key, draft[key].map((item, itemIndex) => itemIndex === index ? value : item));
  const removeListItem = (key: "documents" | "steps", index: number) => update(key, draft[key].filter((_, itemIndex) => itemIndex !== index));
  return <div className="service-editor-backdrop" role="presentation"><section className="service-editor" role="dialog" aria-modal="true" aria-label={service ? "ویرایش خدمت آنلاین" : "خدمت آنلاین جدید"}><header className="service-editor-header"><div><button className="editor-back" onClick={onClose}><ArrowRight size={16} />فهرست خدمات</button><span>{service ? "ویرایش خدمت" : "خدمت محتوایی جدید"}</span><h2>{service ? service.title : "ساخت صفحهٔ جدید خدمت"}</h2><small>این فرم فقط راهنما و مسیر ارتباط بیرونی می‌سازد؛ هیچ API یا فرم حساس ندارد.</small></div><button className="editor-close" aria-label="بستن فرم خدمت" onClick={onClose}><X size={18} /></button></header>
    <nav className="service-editor-tabs" aria-label="بخش‌های فرم خدمت">{(["هویت", "محتوا", "راهنما", "ارتباط"] as const).map((item) => <button key={item} className={section === item ? "active" : ""} onClick={() => setSection(item)}>{item === "هویت" ? <FileText size={15} /> : item === "محتوا" ? <BookOpenCheck size={15} /> : item === "راهنما" ? <ListChecks size={15} /> : <Send size={15} />}{item}</button>)}</nav>
    <main className="service-editor-body">
      {section === "هویت" && <div className="service-form-section"><div className="service-section-heading"><FileText size={18} /><div><b>هویت و انتشار</b><small>عنوان، دسته و URL پایدار صفحهٔ خدمت را مشخص کنید.</small></div></div><div className="service-form-grid"><label>عنوان خدمت<input value={draft.title ?? ""} onChange={(event) => update("title", event.target.value)} placeholder="مثلاً: استعلام خلافی خودرو" autoFocus /></label><label>دستهٔ خدمت<AppSelect value={String(draft.serviceCategoryId)} ariaLabel="دستهٔ خدمت" options={categories.filter((category) => category.is_active || category.id === service?.serviceCategoryId).map((category) => ({ value: String(category.id), label: category.name }))} onChange={(value) => update("serviceCategoryId", Number(value))} /></label><label className="wide">slug صفحه<input dir="ltr" value={draft.slug ?? ""} onChange={(event) => update("slug", event.target.value)} placeholder="vehicle-fines-inquiry" /><small dir="ltr">/services/{draft.slug || "your-service-slug"}</small></label><label className="wide">توضیح کوتاه<textarea value={draft.summary ?? ""} onChange={(event) => update("summary", event.target.value)} placeholder="یک توضیح روشن که روی کارت و ابتدای صفحهٔ خدمت دیده می‌شود." rows={3} /></label></div><div className="service-publish-note"><ShieldCheck size={18} /><div><b>{draft.status === "منتشرشده" ? "وضعیت فعلی: منتشرشده" : "وضعیت فعلی: پیش‌نویس"}</b><small>انتشار فقط همین صفحهٔ راهنما را در محیط بازبینی قابل‌دیدن می‌کند.</small></div></div></div>}
      {section === "محتوا" && <div className="service-form-section"><div className="service-section-heading"><BookOpenCheck size={18} /><div><b>محتوا و راهنمای خدمت</b><small>توضیح کامل قابل‌خواندن در صفحهٔ اختصاصی خدمت را بنویسید.</small></div></div><label className="service-rich-field">راهنمای کامل<textarea value={draft.body ?? ""} onChange={(event) => update("body", event.target.value)} placeholder="شرایط، محدودیت‌ها، نکته‌های مهم و مسیر کلی دریافت راهنمایی را بنویسید." rows={11} /><small>اطلاعات حساس کاربران را در متن یا فرم این خدمت درخواست نکنید.</small></label></div>}
      {section === "راهنما" && <div className="service-form-section"><div className="service-section-heading"><ClipboardCheck size={18} /><div><b>مدارک، مراحل و سوال‌های متداول</b><small>هر مورد یک ردیف مستقل است و در صفحهٔ خدمت به‌صورت قابل‌اسکن نمایش داده می‌شود.</small></div></div><div className="service-guidance-grid"><DynamicList title="مدارک لازم" icon={<ClipboardCheck size={15} />} items={draft.documents} onAdd={() => addListItem("documents")} onChange={(index, value) => setListItem("documents", index, value)} onRemove={(index) => removeListItem("documents", index)} placeholder="مثلاً: کارت ملی مالک" /><DynamicList title="مراحل انجام" icon={<ListChecks size={15} />} items={draft.steps} onAdd={() => addListItem("steps")} onChange={(index, value) => setListItem("steps", index, value)} onRemove={(index) => removeListItem("steps", index)} placeholder="مثلاً: مدارک را آماده کنید" /></div><section className="service-faq-editor"><header><div><CircleHelp size={16} /><b>سوال‌های متداول</b></div><button type="button" onClick={() => update("faq", [...draft.faq, { question: "", answer: "" }])}><Plus size={14} />سوال جدید</button></header>{draft.faq.length ? <div>{draft.faq.map((item, index) => <article key={`faq-${index}`}><input value={item.question ?? ""} onChange={(event) => update("faq", draft.faq.map((faq, faqIndex) => faqIndex === index ? { ...faq, question: event.target.value } : faq))} placeholder="سوال" /><textarea value={item.answer ?? ""} onChange={(event) => update("faq", draft.faq.map((faq, faqIndex) => faqIndex === index ? { ...faq, answer: event.target.value } : faq))} placeholder="پاسخ کوتاه و روشن" rows={3} /><button type="button" aria-label="حذف سوال" onClick={() => update("faq", draft.faq.filter((_, faqIndex) => faqIndex !== index))}><X size={15} /></button></article>)}</div> : <small className="service-inline-empty">در صورت نیاز سوال‌های پرتکرار را اضافه کنید.</small>}</section></div>}
      {section === "ارتباط" && <div className="service-form-section"><div className="service-section-heading"><Send size={18} /><div><b>ارتباط بیرونی</b><small>کاربر پس از خواندن راهنما از مسیر امن انتخاب‌شده با پشتیبانی ارتباط می‌گیرد.</small></div></div><div className="service-form-grid"><label>نوع ارتباط<AppSelect value={draft.contactType} ariaLabel="نوع ارتباط" options={[{ value: "تلگرام", label: "تلگرام" }, { value: "واتس‌اپ", label: "واتس‌اپ" }, { value: "شماره تماس", label: "شماره تماس" }, { value: "لینک بیرونی", label: "لینک بیرونی" }]} onChange={(contactType) => { update("contactType", contactType); if (contactType === "تلگرام") update("ctaLabel", "ادامه در تلگرام"); if (contactType === "واتس‌اپ") update("ctaLabel", "ادامه در واتس‌اپ"); if (contactType === "شماره تماس") update("ctaLabel", "تماس با پشتیبانی"); }} /></label><label>عنوان دکمه<input value={draft.ctaLabel ?? ""} onChange={(event) => update("ctaLabel", event.target.value)} placeholder="دریافت راهنمایی" /></label><label className="wide">مسیر ارتباط<input dir="ltr" value={draft.contactUrl ?? ""} onChange={(event) => update("contactUrl", event.target.value)} placeholder={draft.contactType === "شماره تماس" ? "tel:+982100000000" : "https://t.me/your_channel"} /><small>{draft.contactType === "شماره تماس" ? "برای شماره، الگوی tel:+982100000000 را وارد کنید." : "فقط لینک امن HTTPS پذیرفته می‌شود."}</small></label></div><div className="service-contact-safety"><ShieldCheck size={18} /><div><b>بدون اتصال فنی</b><small>دکمهٔ این صفحه فقط کاربر را به مسیر بیرونی انتخاب‌شده هدایت می‌کند؛ کلید API، token یا دادهٔ حساس در این بخش وجود ندارد.</small></div></div></div>}
    </main>
    {error && <p className="service-editor-error">{error}</p>}<footer className="service-editor-footer"><button className="editor-cancel" disabled={saving} onClick={onClose}>انصراف</button><div><button className="editor-draft" disabled={saving} onClick={() => { void submit("پیش‌نویس"); }}><Save size={15} />{saving ? "در حال ذخیره…" : "ذخیره پیش‌نویس"}</button><button className="editor-publish" disabled={saving} onClick={() => { void submit("منتشرشده"); }}><CheckCircle2 size={15} />{saving ? "در حال ذخیره…" : "انتشار"}</button></div></footer>
  </section></div>;
}

function DynamicList({ title, icon, items, onAdd, onChange, onRemove, placeholder }: { title: string; icon: ReactNode; items: string[]; onAdd: () => void; onChange: (index: number, value: string) => void; onRemove: (index: number) => void; placeholder: string }) { return <section className="service-dynamic-list"><header><div>{icon}<b>{title}</b></div><button type="button" onClick={onAdd}><Plus size={14} />افزودن</button></header>{items.length ? <div>{items.map((item, index) => <label key={`${title}-${index}`}><span>{(index + 1).toLocaleString("fa-IR")}</span><input value={item ?? ""} onChange={(event) => onChange(index, event.target.value)} placeholder={placeholder} /><button type="button" aria-label={`حذف ${title}`} onClick={() => onRemove(index)}><X size={14} /></button></label>)}</div> : <small>هنوز موردی اضافه نشده است.</small>}</section>; }
