// Design: service categories are a small, separate operations workspace. A category is created once,
// then services choose it through the shared custom AppSelect—never through a free-text category field.
import { useEffect, useState, type FormEvent } from "react";
import { ArrowDown, ArrowRight, ArrowUp, CheckCircle2, FolderTree, Pencil, Plus, Save, Trash2, X } from "lucide-react";
import type { ServiceCategoryItem } from "../../../types";
import "./online-services.css";

type CategoryDraft = Pick<ServiceCategoryItem, "name" | "slug" | "description" | "is_active" | "sort_order">;
const emptyDraft: CategoryDraft = { name: "", slug: "", description: "", is_active: true, sort_order: 0 };
const clean = (value: string) => value.trim().replace(/\s+/g, " ");
const persianLatin: Record<string, string> = { "آ": "a", "ا": "a", "ب": "b", "پ": "p", "ت": "t", "ث": "s", "ج": "j", "چ": "ch", "ح": "h", "خ": "kh", "د": "d", "ذ": "z", "ر": "r", "ز": "z", "ژ": "zh", "س": "s", "ش": "sh", "ص": "s", "ض": "z", "ط": "t", "ظ": "z", "ع": "", "غ": "gh", "ف": "f", "ق": "gh", "ک": "k", "گ": "g", "ل": "l", "م": "m", "ن": "n", "و": "v", "ه": "h", "ی": "y", "ء": "", "ئ": "y", "ؤ": "v", "ة": "h", "ۀ": "h", "‌": "-" };
const automaticSlug = (name: string) => {
  const transliterated = Array.from(clean(name)).map((character) => persianLatin[character] ?? character).join("").toLowerCase();
  const slug = transliterated.replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").replace(/-+/g, "-");
  if (slug) return slug.slice(0, 120);
  const source = clean(name) || "service-category";
  const hash = Array.from(source).reduce((total, character) => ((total * 31) + (character.codePointAt(0) ?? 0)) >>> 0, 7);
  return `service-category-${hash.toString(36)}`;
};

export function OnlineServiceCategoriesPage({ rows, onBack, onSave, onDelete }: { rows: ServiceCategoryItem[]; onBack: () => void; onSave: (category: ServiceCategoryItem | null, draft: CategoryDraft) => Promise<void> | void; onDelete: (category: ServiceCategoryItem) => void }) {
  const [editing, setEditing] = useState<ServiceCategoryItem | "new" | null>(null);
  const [orderedRows, setOrderedRows] = useState(rows);
  const [draft, setDraft] = useState<CategoryDraft>(emptyDraft);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [slugIsManual, setSlugIsManual] = useState(false);
  useEffect(() => setOrderedRows([...rows].sort((left, right) => left.sort_order - right.sort_order)), [rows]);
  const open = (category: ServiceCategoryItem | "new") => { const lastCategory = orderedRows[orderedRows.length - 1]; setEditing(category); setError(""); setSlugIsManual(category !== "new"); setDraft(category === "new" ? { ...emptyDraft, sort_order: (lastCategory?.sort_order ?? 0) + 10 } : { name: category.name, slug: category.slug, description: category.description ?? "", is_active: category.is_active, sort_order: category.sort_order }); };
  const submit = async (event: FormEvent) => { event.preventDefault(); const name = clean(draft.name); const slug = clean(draft.slug).toLowerCase(); if (!name) { setError("نام دسته را وارد کنید."); return; } if (slug && !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) { setError("slug باید انگلیسی، کوچک و با خط تیره باشد."); return; } setSaving(true); setError(""); try { await onSave(editing === "new" ? null : editing, { ...draft, name, slug, description: draft.description.trim() }); setEditing(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "ذخیرهٔ دسته انجام نشد."); } finally { setSaving(false); } };
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= orderedRows.length) return; const next = [...orderedRows]; [next[index], next[target]] = [next[target], next[index]]; const normalized = next.map((category, position) => ({ ...category, sort_order: (position + 1) * 10 })); setOrderedRows(normalized); void Promise.all([onSave(normalized[index], normalized[index]), onSave(normalized[target], normalized[target])]).catch((cause) => { setError(cause instanceof Error ? cause.message : "ثبت ترتیب دسته انجام نشد."); setOrderedRows(rows); }); };

  return <section className="services-workspace">
    <header className="services-command compact-category-command"><div><span><FolderTree size={14} />ساختار خدمات آنلاین</span><h1>دسته‌های خدمات</h1><p>دسته را بسازید و سپس خدمت را به آن متصل کنید.</p></div><div className="category-command-actions"><button className="category-back-button" onClick={onBack}><ArrowRight size={15} />خدمات آنلاین</button><button className="service-primary" onClick={() => open("new")}><Plus size={15} />دستهٔ جدید</button></div></header>
    <section className="service-list-panel service-category-list"><header><span>دسته‌ها</span><small>{orderedRows.length.toLocaleString("fa-IR")} مورد</small></header>{orderedRows.length ? <div>{orderedRows.map((category, index) => <article key={category.id} className="service-category-row"><span className="service-file-mark"><FolderTree size={15} /></span><div className="service-list-copy"><b>{category.name}</b><small dir="ltr">/services/category/{category.slug}</small></div><em className={category.is_active ? "published" : "draft"}>{category.is_active ? "فعال" : "غیرفعال"}</em><span className="service-contact">{(category.services_count ?? 0).toLocaleString("fa-IR")} خدمت</span><div className="category-row-actions"><button type="button" className="category-icon-button" aria-label={`بالا بردن ${category.name}`} title="بالا بردن" disabled={index === 0} onClick={() => move(index, -1)}><ArrowUp size={14} /></button><button type="button" className="category-icon-button" aria-label={`پایین بردن ${category.name}`} title="پایین بردن" disabled={index === orderedRows.length - 1} onClick={() => move(index, 1)}><ArrowDown size={14} /></button><button type="button" className="category-icon-button" aria-label={`ویرایش ${category.name}`} title="ویرایش" onClick={() => open(category)}><Pencil size={14} /></button><button type="button" className="category-icon-button category-delete-button" aria-label={`حذف ${category.name}`} title={(category.services_count ?? 0) > 0 ? "ابتدا خدمت‌های این دسته را منتقل کنید" : "حذف"} disabled={(category.services_count ?? 0) > 0} onClick={() => onDelete(category)}><Trash2 size={14} /></button></div></article>)}</div> : <div className="services-empty"><FolderTree size={24} /><b>هنوز دسته‌ای ساخته نشده است.</b><button onClick={() => open("new")}>ساخت اولین دسته</button></div>}</section>
    {editing && <div className="service-editor-backdrop" role="presentation"><form className="service-editor" role="dialog" aria-modal="true" aria-label="ویرایش دستهٔ خدمات" onSubmit={submit}><header className="service-editor-header"><div><span>{editing === "new" ? "دستهٔ جدید" : "ویرایش دسته"}</span><h2>{editing === "new" ? "ساخت دستهٔ خدمات" : editing.name}</h2><small>این دسته در مگامنو و صفحهٔ خدمات، فقط هنگام فعال‌بودن و داشتن خدمت منتشرشده نمایش داده می‌شود.</small></div><button type="button" className="editor-close" onClick={() => setEditing(null)}><X size={18} /></button></header><main className="service-editor-body"><div className="service-form-section"><div className="service-form-grid"><label>نام دسته<input value={draft.name} onChange={(event) => { const name = event.target.value; setDraft((current) => ({ ...current, name, slug: slugIsManual ? current.slug : automaticSlug(name) })); }} placeholder="مثلاً: خدمات خودرو" autoFocus /></label><label>slug دسته<input dir="ltr" value={draft.slug} onChange={(event) => { const slug = event.target.value; setSlugIsManual(Boolean(slug.trim())); setDraft((current) => ({ ...current, slug: slug.trim() ? slug : automaticSlug(current.name) })); }} placeholder="خودکار از نام دسته ساخته می‌شود" /><small dir="ltr">/services/category/{draft.slug || "category-slug"}</small></label><label className="wide">توضیح کوتاه<textarea rows={3} value={draft.description ?? ""} onChange={(event) => setDraft((current) => ({ ...current, description: event.target.value }))} placeholder="توضیح داخلی اختیاری برای مدیریت بهتر دسته" /></label></div><button type="button" className={`editor-draft mt-4 ${draft.is_active ? "" : "opacity-60"}`} onClick={() => setDraft((current) => ({ ...current, is_active: !current.is_active }))}>{draft.is_active ? <CheckCircle2 size={15} /> : <X size={15} />}{draft.is_active ? "دسته فعال است" : "دسته غیرفعال است"}</button></div></main>{error && <p className="service-editor-error">{error}</p>}<footer className="service-editor-footer"><button type="button" className="editor-cancel" disabled={saving} onClick={() => setEditing(null)}>انصراف</button><button className="editor-publish" disabled={saving} type="submit"><Save size={15} />{saving ? "در حال ذخیره…" : "ذخیرهٔ دسته"}</button></footer></form></div>}
  </section>;
}
